### ISSUE TITLE
Error installing 0.54.2 on Synology NAS: "failed to get urandom"

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#1766]
> Took some time to retry installing VanDAM/Manyfold on a Synology NAS. I've tried the 0.54.2 image but it still seems to crash on getting some required ruby gems, this time the `mittsu` gem.

```
2024-01-25T12:34:47.191148606Z,stdout,(See full trace by running task with --trace)
2024-01-25T12:34:47.191085748Z,stdout,bin/rails:4:in `<main>'
2024-01-25T12:34:47.191006279Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.190935981Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.190834493Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.190763604Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
2024-01-25T12:34:47.190695946Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
2024-01-25T12:34:47.190621877Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
2024-01-25T12:34:47.190549229Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
2024-01-25T12:34:47.190488660Z,stdout,/usr/src/app/Rakefile:4:in `<main>'
2024-01-25T12:34:47.190425871Z,stdout,/usr/src/app/Rakefile:4:in `require_relative'
2024-01-25T12:34:47.190344003Z,stdout,/usr/src/app/config/application.rb:7:in `<main>'
2024-01-25T12:34:47.190273665Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
2024-01-25T12:34:47.190208056Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
2024-01-25T12:34:47.190142347Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
2024-01-25T12:34:47.190071889Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
2024-01-25T12:34:47.190005360Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
2024-01-25T12:34:47.189936642Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
2024-01-25T12:34:47.189862273Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.189774015Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189699947Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189626078Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu.rb:10:in `<main>'
2024-01-25T12:34:47.189552900Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.189472172Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189403613Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189330954Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects.rb:4:in `<main>'
2024-01-25T12:34:47.189259476Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.189185428Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189116819Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.189041391Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:1:in `<main>'
2024-01-25T12:34:47.188963272Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:2:in `<module:Mittsu>'
2024-01-25T12:34:47.188886164Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:16:in `<class:Sprite>'
2024-01-25T12:34:47.188784396Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:16:in `new'
2024-01-25T12:34:47.188709827Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/core/buffer_geometry.rb:15:in `initialize'
2024-01-25T12:34:47.188649209Z,stdout,failed to get urandom
2024-01-25T12:34:47.188588610Z,stdout,Caused by:
2024-01-25T12:34:47.188531051Z,stdout,
2024-01-25T12:34:47.188469453Z,stdout,bin/rails:4:in `<main>'
2024-01-25T12:34:47.188394144Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.188322416Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.188250467Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.188163589Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
2024-01-25T12:34:47.188089401Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
2024-01-25T12:34:47.188018842Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
2024-01-25T12:34:47.187943484Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
2024-01-25T12:34:47.187879365Z,stdout,/usr/src/app/Rakefile:4:in `<main>'
2024-01-25T12:34:47.187796827Z,stdout,/usr/src/app/Rakefile:4:in `require_relative'
2024-01-25T12:34:47.187731688Z,stdout,/usr/src/app/config/application.rb:7:in `<main>'
2024-01-25T12:34:47.187666219Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
2024-01-25T12:34:47.187601751Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
2024-01-25T12:34:47.187535522Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
2024-01-25T12:34:47.187466864Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
2024-01-25T12:34:47.187393815Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
2024-01-25T12:34:47.187323887Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:59:in `block (2 levels) in require'
2024-01-25T12:34:47.187241028Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:63:in `rescue in block (2 levels) in require'
2024-01-25T12:34:47.187176280Z,stdout,Bundler Error Backtrace:
2024-01-25T12:34:47.187113881Z,stdout,bin/rails:4:in `<main>'
2024-01-25T12:34:47.187034853Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.186875826Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.186433135Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.186342327Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
2024-01-25T12:34:47.186269449Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
2024-01-25T12:34:47.186194400Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
2024-01-25T12:34:47.186121002Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
2024-01-25T12:34:47.186042173Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
2024-01-25T12:34:47.185971075Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:125:in `load_rakefile'
2024-01-25T12:34:47.185882397Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
2024-01-25T12:34:47.185785829Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:126:in `block in load_rakefile'
2024-01-25T12:34:47.185713290Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/application.rb:734:in `raw_load_rakefile'
2024-01-25T12:34:47.185641492Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
2024-01-25T12:34:47.185566203Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load'
2024-01-25T12:34:47.185501805Z,stdout,/usr/src/app/Rakefile:4:in `<main>'
2024-01-25T12:34:47.185434996Z,stdout,/usr/src/app/Rakefile:4:in `require_relative'
2024-01-25T12:34:47.185360408Z,stdout,/usr/src/app/config/application.rb:7:in `<main>'
2024-01-25T12:34:47.185282529Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler.rb:187:in `require'
2024-01-25T12:34:47.185213831Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `require'
2024-01-25T12:34:47.185142492Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:44:in `each'
2024-01-25T12:34:47.185075574Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `block in require'
2024-01-25T12:34:47.185007305Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:55:in `each'
2024-01-25T12:34:47.184929327Z,stdout,/usr/local/bundle/gems/bundler-2.4.13/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
2024-01-25T12:34:47.184831729Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.184763520Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.184681902Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.184608394Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu.rb:10:in `<main>'
2024-01-25T12:34:47.184536335Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.184467467Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.184381868Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.184156513Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects.rb:4:in `<main>'
2024-01-25T12:34:47.184065145Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
2024-01-25T12:34:47.183996646Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.183921968Z,stdout,<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
2024-01-25T12:34:47.183827360Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:1:in `<main>'
2024-01-25T12:34:47.183753991Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:2:in `<module:Mittsu>'
2024-01-25T12:34:47.183673133Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:16:in `<class:Sprite>'
2024-01-25T12:34:47.183597325Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/objects/sprite.rb:16:in `new'
2024-01-25T12:34:47.183519176Z,stdout,/usr/src/app/vendor/bundle/ruby/3.2.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/core/buffer_geometry.rb:15:in `initialize'
2024-01-25T12:34:47.183442028Z,stdout,/usr/local/lib/ruby/3.2.0/random/formatter.rb:171:in `uuid'
2024-01-25T12:34:47.183373149Z,stdout,/usr/local/lib/ruby/3.2.0/random/formatter.rb:74:in `random_bytes'
2024-01-25T12:34:47.183290441Z,stdout,/usr/local/lib/ruby/3.2.0/securerandom.rb:55:in `gen_random_openssl'
2024-01-25T12:34:47.183219633Z,stdout,/usr/local/lib/ruby/3.2.0/securerandom.rb:55:in `urandom'
2024-01-25T12:34:47.183155814Z,stdout,Backtrace for gem load error is:
2024-01-25T12:34:47.183077786Z,stdout,Gem Load Error is: failed to get urandom
2024-01-25T12:34:47.182956938Z,stdout,Bundler::GemRequireError: There was an error while trying to load the gem 'mittsu'. (Bundler::GemRequireError)
2024-01-25T12:34:47.182473668Z,stdout,rails aborted!
2024-01-25T12:34:42.639210931Z,stdout,Preparing database...
```

_Originally posted by @mvkalsbeek in https://github.com/manyfold3d/manyfold/issues/1239#issuecomment-1910128039_

**Comment by Floppy** [comment]
I found this similar report on Synology, Docker, and Ruby 3.1, probably a new issue related to that: https://github.com/pglombardo/PasswordPusher/discussions/647. I'll have a look.
