### ISSUE TITLE
TypeError: no implicit conversion of Array into String (TypeError) (running `bin/dev`)

### ISSUE THREAD

**Issue by RemcoGoy** [manyfold3d/manyfold#1998]
**Describe the bug**
TypeError when running `bin/dev`

```bash
rails aborted!
TypeError: no implicit conversion of Array into String (TypeError)

        File.basename(match)
```

**To Reproduce**
1. Clone the repo
2. Run bin/dev

**Expected behavior**
The application to start up

**Screenshots**
![image](https://github.com/manyfold3d/manyfold/assets/34539109/5ebe5e7b-410d-4cb8-8251-c594f53e96c7)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1 (M3 Pro)

**Smartphone (please complete the following information):**

**Additional context**
```bash
❯ bin/dev --trace
== Installing dependencies ==
The Gemfile's dependencies are satisfied

== Preparing database ==
rails aborted!
TypeError: no implicit conversion of Array into String (TypeError)

        File.basename(match)
                      ^^^^^
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/renderers/glfw_lib.rb:43:in `basename'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/renderers/glfw_lib.rb:43:in `file'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/renderers/glfw_window.rb:7:in `<main>'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/renderers/opengl_renderer.rb:9:in `<main>'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu/renderers.rb:1:in `<main>'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/bundler/gems/mittsu-7f44c468f9d6/lib/mittsu.rb:11:in `<main>'
<internal:/Users/remcogoyvaerts/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/Users/remcogoyvaerts/.rvm/rubies/ruby-3.3.0/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:55:in `each'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:55:in `block in require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:44:in `each'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler/runtime.rb:44:in `require'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bundler-2.5.6/lib/bundler.rb:187:in `require'
/Users/remcogoyvaerts/Documents/personalProjects/manyfold/config/application.rb:25:in `<main>'
/Users/remcogoyvaerts/Documents/personalProjects/manyfold/Rakefile:4:in `require_relative'
/Users/remcogoyvaerts/Documents/personalProjects/manyfold/Rakefile:4:in `<main>'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/railties-7.0.8.1/lib/rails/command.rb:51:in `invoke'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/railties-7.0.8.1/lib/rails/commands.rb:18:in `<main>'
/Users/remcogoyvaerts/.rvm/gems/ruby-3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)

== Command ["bin/rails db:prepare:with_data"] failed ==
```

**Comment by RemcoGoy** [comment]
Update;

It looks like I kinda could work around it by disabling the 'db:prepare:with_data' command, but now I'm onto another issue

**Comment by RemcoGoy** [comment]
@Floppy , thanks! I'll try it out soon!

**Comment by RemcoGoy** [comment]
@Floppy , the mittsu instructions worked, thanks a lot!

**Comment by Floppy** [comment]
Great - I need to make that much more obvious in the documentation!
