### ISSUE TITLE
Bricked Instance after update because of enforced email check

### ISSUE THREAD

**Issue by ToasterUwU** [manyfold3d/manyfold#2014]
**Describe the bug**
The App Docker container just crashes and reboots in an endless cycle, i have found the issue already but dont know how to fix it.

**To Reproduce**
1. Go to the admin panel
2. Change it so that its required to login (i did this because i can reach my instance from the internet)
3. Set the email of the account to something that isnt an email (in my case 'Aki')
4. Stop, update to newest version, start, see the error

**Expected behavior**
An invalid email should be a warning, not a fatal error, especially because manyfold doesnt send emails, and because a username in the email field was valid before and can brick an instance after an update like in my case.

```
manyfold_app_1 exited with code 1
app_1    | Illegal option -p
app_1    | sh: lspci: not found
app_1    | Illegal option -p
app_1    | sh: lspci: not found
app_1    | rails aborted!
app_1    | StandardError: An error has occurred, this and all later migrations canceled: (StandardError)
app_1    | 
app_1    | Validation failed: Email is invalid
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/validations.rb:80:in `raise_validation_error'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/validations.rb:53:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:302:in `block in save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:302:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/suppressor.rb:54:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:782:in `block in update!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:780:in `update!'
app_1    | /usr/src/app/db/data/20240322150022_set_admin_password_reset_token.rb:6:in `up'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:908:in `public_send'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:908:in `exec_migration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:888:in `block in migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:887:in `migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1095:in `migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:209:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1460:in `ddl_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1370:in `run_without_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1323:in `block in run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1477:in `with_advisory_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1323:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/migration_context.rb:29:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/data_migrator.rb:69:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:59:in `run_migration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:178:in `block in migrate_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:177:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:177:in `migrate_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:208:in `block (2 levels) in prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:89:in `with_temporary_pool'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:188:in `block in prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:554:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:553:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:185:in `prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/tasks/databases.rake:153:in `block (3 levels) in <main>'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/command.rb:51:in `invoke'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands.rb:18:in `<main>'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app_1    | 
app_1    | Caused by:
app_1    | ActiveRecord::RecordInvalid: Validation failed: Email is invalid (ActiveRecord::RecordInvalid)
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/validations.rb:80:in `raise_validation_error'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/validations.rb:53:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:302:in `block in save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:302:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/suppressor.rb:54:in `save!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:782:in `block in update!'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/persistence.rb:780:in `update!'
app_1    | /usr/src/app/db/data/20240322150022_set_admin_password_reset_token.rb:6:in `up'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:908:in `public_send'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:908:in `exec_migration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:889:in `block (2 levels) in migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:888:in `block in migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:887:in `migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1095:in `migrate'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1409:in `block in execute_migration_in_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.0.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/transactions.rb:209:in `transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1460:in `ddl_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1408:in `execute_migration_in_transaction'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1370:in `run_without_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1323:in `block in run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1481:in `block in with_advisory_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1496:in `with_advisory_lock_connection'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1477:in `with_advisory_lock'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/migration.rb:1323:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/migration_context.rb:29:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/data_migrator.rb:69:in `run'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:59:in `run_migration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:178:in `block in migrate_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:177:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:177:in `migrate_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:208:in `block (2 levels) in prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:89:in `with_temporary_pool'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:188:in `block in prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:557:in `block (2 levels) in each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:554:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:554:in `block in each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:553:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/tasks/database_tasks.rb:553:in `each_current_configuration'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/lib/data_migrate/database_tasks.rb:185:in `prepare_all_with_data'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/bundler/gems/data-migrate-b2cbb40b5e13/tasks/databases.rake:153:in `block (3 levels) in <main>'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:59:in `with_application'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/command.rb:51:in `invoke'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/railties-7.0.8.1/lib/rails/commands.rb:18:in `<main>'
app_1    | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
app_1    | Tasks: TOP => db:prepare:with_data
app_1    | (See full trace by running task with --trace)
app_1    | == Data =======================================================================
app_1    | == 20240322150022 SetAdminPasswordResetToken: migrating =======================
manyfold_app_1 exited with code 1
```

**Comment by Floppy** [comment]
OK, had a look into the detail, and I've got a fix which will go into the next release, later on today. Once that's in, it should guide you through fixing up your admin user so it all works again. Let me know if it works!

**Comment by ToasterUwU** [comment]
I never enabled multi user support at all, i just set the email to a username, so i dont have to bother typing in the entire email just for a login into a thing i host myself and dont give anyone else access to. 
I assumed it will be fine since there was no email functionality in sight. And yes, it let me put a username in the email field, and i did because thats the field for the login, or at least it was at the time where i did that.

**Comment by ToasterUwU** [comment]
Well, one issue i have with the new solution is that i need to change my password as well, since it cant be the current one for some reason. That shouldnt happen since i didnt come to that page because of a forgotten password but because of a invalid email. 

But its not that big of an issue, i can just change and change back after all.

**Comment by ToasterUwU** [comment]
Ok, worked fine. My instance is running normally again, thanks for the quick fix!

**Comment by Floppy** [comment]
The main function for that page is to set a proper password, because most users won't have done so yet. The ability to fix your email problem was just a side effect. Glad it worked!

**Comment by Floppy** [comment]
> I never enabled multi user support at all, i just set the email to a username, so i dont have to bother typing in the entire email just for a login into a thing i host myself and dont give anyone else access to. I assumed it will be fine since there was no email functionality in sight. And yes, it let me put a username in the email field, and i did because thats the field for the login, or at least it was at the time where i did that.

Thank you for that, I'll see if there's any sharp edges that I need to file off in that process. It's been awkward to work out how to migrate people securely to the expanded user system, so all feedback is great, thank you!
