### ISSUE TITLE
Bulk Edit - Causes fatal error when not checking any Models

### ISSUE THREAD

**Issue by ToasterUwU** [manyfold3d/manyfold#2061]
**Describe the bug**
When i go to Bulk edit, but dont mark any of the models to be included in that action, it shows a error page that tells me to check the log. Not a pop up, nothing that gives the user the feeling they did something wrong. 

**To Reproduce**
1. Go to Models
2. Click on "Bulk Edit"
3. Dont check any of the models
4. Confirm and see the error

**Expected behavior**
There should be a pop up that tells the user that they didnt check any models, so nothing will be done. 

**Screenshots**
![image](https://github.com/manyfold3d/manyfold/assets/43654377/7f052af2-64b0-460a-8f5e-da86426b2b17)

**Desktop**
 - OS: Linux
 - Browser: Firefox

**Additional context**
I tested it with not having any models and any actions, and with telling it to organize all files (which are 0, since i didnt check any of them). 
I assume there is no check for the list of models being empty, and then it errors out instead of warning the user.

**Log**
```
W, [2024-04-21T11:37:43.128826 #113]  WARN -- : [a514370f-ec03-484c-a734-955bc344b58e] Scoped order is ignored, it's forced to be batch order.
I, [2024-04-21T11:37:43.143470 #113]  INFO -- : [a514370f-ec03-484c-a734-955bc344b58e] method=GET path=/models/edit format=html controller=ModelsController action=bulk_edit status=200 allocations=216762 duration=912.44 view=640.59 db=220.59
I, [2024-04-21T11:37:47.988557 #113]  INFO -- : [644a118c-9bbb-47fc-853d-fa469c63a3f4] method=PATCH path=/models/update format=html controller=ModelsController action=bulk_update status=500 allocations=2150 duration=16.34 view=0.00 db=4.47 location=https://manyfold.example.com/models/edit
F, [2024-04-21T11:37:47.991522 #113] FATAL -- : [644a118c-9bbb-47fc-853d-fa469c63a3f4]   
[644a118c-9bbb-47fc-853d-fa469c63a3f4] Pundit::PolicyScopingNotPerformedError (ModelsController):
[644a118c-9bbb-47fc-853d-fa469c63a3f4]   
[644a118c-9bbb-47fc-853d-fa469c63a3f4] pundit (2.3.1) lib/pundit/authorization.rb:49:in `verify_policy_scoped'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:400:in `block in make_lambda'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:236:in `block in halting_and_conditional'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:599:in `block in invoke_after'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:599:in `each'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:599:in `invoke_after'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:108:in `run_callbacks'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/abstract_controller/callbacks.rb:233:in `process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal/rescue.rb:23:in `process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/notifications.rb:206:in `block in instrument'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/notifications.rb:206:in `instrument'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activerecord (7.0.8.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/abstract_controller/base.rb:151:in `process'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionview (7.0.8.1) lib/action_view/rendering.rb:39:in `process'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal.rb:188:in `dispatch'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_controller/metal.rb:251:in `dispatch'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/journey/router.rb:32:in `each'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/journey/router.rb:32:in `serve'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/routing/route_set.rb:852:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] flipper (1.2.2) lib/flipper/middleware/memoizer.rb:87:in `memoized_call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] flipper (1.2.2) lib/flipper/middleware/memoizer.rb:45:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rails-settings-cached (2.9.4) lib/rails-settings/middleware.rb:9:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack-contrib (2.4.0) lib/rack/contrib/locale.rb:21:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/etag.rb:27:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/conditional_get.rb:40:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/head.rb:12:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/cookies.rb:704:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/callbacks.rb:99:in `run_callbacks'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] lograge (0.14.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] railties (7.0.8.1) lib/rails/rack/logger.rb:25:in `block in call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/tagged_logging.rb:37:in `tagged'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] activesupport (7.0.8.1) lib/active_support/tagged_logging.rb:99:in `tagged'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] railties (7.0.8.1) lib/rails/rack/logger.rb:25:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/method_override.rb:24:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/runtime.rb:22:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/static.rb:23:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/sendfile.rb:110:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] actionpack (7.0.8.1) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] railties (7.0.8.1) lib/rails/engine.rb:530:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/urlmap.rb:74:in `block in call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/urlmap.rb:58:in `each'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] rack (2.2.9) lib/rack/urlmap.rb:58:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
[644a118c-9bbb-47fc-853d-fa469c63a3f4] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'
```

**Comment by Floppy** [comment]
I also spotted last night that I broke this. 

Are you running the latest code? I didn't think it was broken in the release yet... anyway, I'll fix it this evening and a release should be out shortly after that.

Thanks for the report!

**Comment by Floppy** [comment]
Oh, actually, looking at the log, this isn't what I thought it was. I'll get a fix out though.
