### ISSUE TITLE
All Pooled Connections are in use

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2288]
**Describe the bug**

When uploading multiple files in a row, I have started to see many messages like the following:

```
could not obtain a connection from the pool within 5.000 seconds (waited 5.092 seconds); all pooled connections were in use
```

![image](https://github.com/manyfold3d/manyfold/assets/46961848/5f832a62-5775-43c9-b660-2adee95f5520)

I checked that all of my containers have enough resources. Storage is all on SSD and my server is fairly powerful.

**To Reproduce**
1.  Upload Model
2. Upload Another Model
3. Upload succeeds but model has not been detected

**Expected behavior**
Uploading files one after another should not cause problems on powerful hardware.

**Screenshots**
![image](https://github.com/manyfold3d/manyfold/assets/46961848/5f832a62-5775-43c9-b660-2adee95f5520)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version `126.0.1`

**Additional context**
Does not seem to be a performance issue with postgres or redis either.

**Comment by Floppy** [comment]
Oh dear. That's not right!

Is there anything in the logs to show which pool? I assume it's the postgres conneciton pool; what's your database connection configuration?

**Comment by aneurinprice** [comment]
Relevent logs:

```
21:16:59 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.2.4/lib/sidekiq/component.rb:19:in `block in safe_thread'
21:17:00 worker.1 | 2024-06-19T21:17:00.700Z pid=38 tid=13sy class=Analysis::AnalyseModelFileJob jid=6667b653d712686561a7ad1a elapsed=9.101 INFO: fail
21:17:01 worker.1 | 2024-06-19T21:17:01.014Z pid=38 tid=13sy WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"analysis","class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Analysis::AnalyseModelFileJob","args":[{"job_class":"Analysis::AnalyseModelFileJob","job_id":"b5b758eb-853e-42fd-be48-8b5cf7dbf365","provider_job_id":null,"queue_name":"analysis","priority":null,"arguments":[6933],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-06-19T21:15:12Z"}],"jid":"6667b653d712686561a7ad1a","created_at":1718831712.8749862,"enqueued_at":1718831712.8750412,"error_message":"could not obtain a connection from the pool within 5.000 seconds (waited 5.194 seconds); all pooled connections were in use","error_class":"ActiveRecord::ConnectionTimeoutError","processor":"manyfold-manyfold-0:38","failed_at":1718831820.2010674}}
21:17:01 worker.1 | 2024-06-19T21:17:01.316Z pid=38 tid=13sy WARN: ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.194 seconds); all pooled connections were in use
21:17:01 worker.1 | 2024-06-19T21:17:01.558Z pid=38 tid=13sy WARN: app/models/model_file.rb:15:in `block in <class:ModelFile>'
21:17:01 worker.1 | app/jobs/analysis/analyse_model_file_job.rb:7:in `perform'
21:17:02 worker.1 | 2024-06-19T21:17:02.391Z pid=38 tid=13vu class=Analysis::AnalyseModelFileJob jid=eb2be047456caea7f12178d2 INFO: start
21:17:02 worker.1 | 2024-06-19T21:17:02.624Z pid=38 tid=13vu class=Analysis::AnalyseModelFileJob jid=eb2be047456caea7f12178d2 INFO: Performing Analysis::AnalyseModelFileJob (Job ID: 7e004df9-9063-475c-a960-3741e7046590) from Sidekiq(analysis) enqueued at 2024-06-19T21:15:27Z with arguments: 6935
21:17:10 worker.1 | 2024-06-19T21:17:10.057Z pid=38 tid=13vu class=Analysis::AnalyseModelFileJob jid=eb2be047456caea7f12178d2 ERROR: Error performing Analysis::AnalyseModelFileJob (Job ID: 7e004df9-9063-475c-a960-3741e7046590) from Sidekiq(analysis) in 7432.81ms: ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.043 seconds); all pooled connections were in use):
21:17:10 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:126:in `block in wait_poll'
21:17:10 worker.1 | <internal:kernel>:187:in `loop'
21:17:10 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:115:in `wait_poll'
21:17:10 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:76:in `internal_poll'
21:17:10 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:202:in `internal_poll'
21:17:10 worker.1 | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool/queue.rb:71:in `block in poll'
21:17:10 worker.1 | /usr/local/lib/ruby/3.3.0/monitor.rb:201:in `synchronize'
```

```
spec:
  containers:
  - env:
    - name: DATABASE_HOST
      value: manyfold-postgresql
    - name: DATABASE_USER
      value: manyfold
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: manyfold-postgresql
    - name: DATABASE_NAME
      value: manyfold
    - name: SECRET_KEY_BASE
      value: <redacted>
    - name: REDIS_URL
      value: redis://manyfold-redis-master:6379/1
      ```
      
     While looking at this, I stumbled accross the modular string generation that I hacked together in the entrypoint.
     
```
	export DATABASE_URL="postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME}?pool=5"
```

Is it as simple as parametising the pool value? If so, I can put in a PR for that tomorrow.

**Comment by Floppy** [comment]
I'm no expert in the pool config, but yeah, the first thing I'd try is increasing that...

**Comment by aneurinprice** [comment]
> I'm no expert in the pool config, but yeah, the first thing I'd try is increasing that...

I built from main with my changes and it seems to work. Although now there is a maximum upload size of 256 MB. Due to this I cannot test properly, is this expected behavior? I was unable to find any setting for this in the app.

**Comment by Floppy** [comment]
Ah, yes, if you're on main. That's coming in the next release, it's a security thing - I'm writing the docs now! You can set the `MAX_FILE_UPLOAD_SIZE` env to a larger byte size to increase it.

**Comment by aneurinprice** [comment]
Saw the release this morning, looks great! Is there a list of all of the new ENV vars? I'd like to incorporate all of them into the container image.

**Comment by Floppy** [comment]
Yep, docs have just gone up at https://manyfold.app/sysadmin/security

**Comment by aneurinprice** [comment]
Aha! You wonderful person. These tweaks have fixed the problem. I will have a PR in shortly to variablise the connection pool.

**Comment by Floppy** [comment]
excellent, thanks!

**Comment by aneurinprice** [comment]
Resolved in https://github.com/manyfold3d/manyfold/pull/2293
