### ISSUE TITLE
Allow ignoring SMTP Host SSL errors

### ISSUE THREAD

**Issue by ToasterUwU** [manyfold3d/manyfold#2380]
**Is your feature request related to a problem? Please describe.**
I just tried the SMTP integration for reset password emails. Really cool idea, but if my SMTP server is in the local net and i dont have DNS setup in a specific way to where an actual domain will point to a local net address, i will not be able to use this.
When i tried to send me a reset password email for testing this feature, i got a error page, and in the log it says:

```
F, [2024-07-11T13:17:34.500187 #229] FATAL -- : [93efcad3-02b4-40f7-9fb4-966f0407926a]   
[93efcad3-02b4-40f7-9fb4-966f0407926a] OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 peeraddr=192.168.178.3:25 state=error: certificate verify failed (hostname mismatch)):
[93efcad3-02b4-40f7-9fb4-966f0407926a]   
[93efcad3-02b4-40f7-9fb4-966f0407926a] app/controllers/users/passwords_controller.rb:21:in `create'
[93efcad3-02b4-40f7-9fb4-966f0407926a] app/controllers/application_controller.rb:72:in `switch_locale'
```

**Describe the solution you'd like**
I would like another environment variable in the SMTP section that is something like "SMTP_IGNORE_SSL_ERRORS", so that i can work around this issue in a clean manner.

**Describe alternatives you've considered**
Alternatively this could also be a "SMTP_VERIFY_SSL" where it needs to be actively set to "disable", but thats a thing you need to decide.

**Comment by Floppy** [comment]
Pretty sure there's an ActionMailer setting for this, I'll see if I can expose it 👍🏻
