### ISSUE TITLE
Validation failed: Actor must exist

### ISSUE THREAD

**Issue by aneurinprice** [manyfold3d/manyfold#2556]
**Describe the bug**
Hi james,

Thank for getting those duplication bugs sorted. Unfortunately I seem to be running into a new one(s).

Upon uploading, the dialogue seems happy but the model never appears, looking at the logs we get:

![image](https://github.com/user-attachments/assets/df8b183f-890b-4659-a6a5-401e7bc9f3f5)

![image](https://github.com/user-attachments/assets/cac19c58-20ea-4527-a163-fcaf48320e12)

Sorry for pestering you!

**Comment by Floppy** [comment]
Crap, that's on 0.76.0 as well. Thanks for flagging it, I'll fix asap.

**Comment by Floppy** [comment]
OK, I don't see that problem on either of my instances, which must be in a different state than yours regarding federails actors. Can you see any more detail on the error backtrace in the log files?

**Comment by aneurinprice** [comment]
```
17:16:37 default_worker.1     | 2024-08-21T17:16:37.384Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c INFO: start
17:16:37 default_worker.1     | 2024-08-21T17:16:37.384Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c INFO: Performing ProcessUploadedFileJob (Job ID: 40e1a8d2-9c9d-47f1-8f88-01fab9f2eb86) from Sidekiq(default) enqueued at 2024-08-21T12:54:42.787162398Z with arguments: 1, {"id"=>"99cd5e222e75801eb0e5a57c3f57520e.zip", "storage"=>"cache", "metadata"=>{"filename"=>"ok-trophy-model_files.zip", "size"=>5041038, "mime_type"=>"application/zip"}}
17:16:37 default_worker.1     | 2024-08-21T17:16:37.385Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c WARN: Scoped order is ignored, it's forced to be batch order.
17:16:37 default_worker.1     | 2024-08-21T17:16:37.399Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c ERROR: Error performing ProcessUploadedFileJob (Job ID: 40e1a8d2-9c9d-47f1-8f88-01fab9f2eb86) from Sidekiq(default) in 14.8ms: ActiveRecord::RecordInvalid (Validation failed: Actor must exist):
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:84:in `raise_validation_error'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:55:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `block in save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:56:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:55:in `create!'
17:16:37 default_worker.1     | /usr/src/app/app/models/concerns/followable.rb:26:in `post_creation_activity'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:403:in `block in make_lambda'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:239:in `block in halting_and_conditional'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:602:in `block in invoke_after'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:602:in `each'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:602:in `invoke_after'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:111:in `run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_create_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:445:in `_create_record'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:114:in `_create_record'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1221:in `create_or_update'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `block in create_or_update'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/autosave_association.rb:375:in `around_save_collection_association'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_save_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `create_or_update'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:125:in `create_or_update'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:751:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:55:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `block in save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:313:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:56:in `save!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:906:in `block in update!'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:904:in `update!'
17:16:37 default_worker.1     | /usr/src/app/app/jobs/process_uploaded_file_job.rb:17:in `perform'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:69:in `block in _perform_job'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:68:in `_perform_job'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:32:in `_perform_job'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:52:in `perform_now'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `block in perform_now'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:40:in `block in instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `block in instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/notifications.rb:206:in `instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:39:in `instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.4/lib/active_record/railties/job_runtime.rb:11:in `instrument'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/instrumentation.rb:26:in `perform_now'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `block in perform_now'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `block in tagged'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:39:in `tagged'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/tagged_logging.rb:135:in `tagged'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/broadcast_logger.rb:240:in `method_missing'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:25:in `tag_logger'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/logging.rb:18:in `perform_now'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:30:in `block in execute'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `instance_exec'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/execution.rb:28:in `execute'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activejob-7.1.3.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:70:in `perform'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:220:in `execute_job'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:185:in `block (4 levels) in process'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:180:in `traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/job/interrupt_handler.rb:9:in `call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/metrics/tracking.rb:26:in `track'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/metrics/tracking.rb:134:in `call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-failures-1.0.4/lib/sidekiq/failures/middleware.rb:9:in `call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:182:in `traverse'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/middleware/chain.rb:173:in `invoke'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:184:in `block (3 levels) in process'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:145:in `block (6 levels) in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/job_retry.rb:118:in `local'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:144:in `block (5 levels) in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/rails.rb:16:in `block in call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:77:in `block in wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/activesupport-7.1.3.4/lib/active_support/reloader.rb:74:in `wrap'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/rails.rb:15:in `call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:139:in `block (4 levels) in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:281:in `stats'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:134:in `block (3 levels) in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/job_logger.rb:23:in `call'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:133:in `block (2 levels) in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/job_retry.rb:85:in `global'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:132:in `block in dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/job_logger.rb:50:in `prepare'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:131:in `dispatch'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:183:in `block (2 levels) in process'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:182:in `handle_interrupt'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:182:in `block in process'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:181:in `handle_interrupt'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:181:in `process'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:86:in `process_one'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/processor.rb:76:in `run'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/component.rb:10:in `watchdog'
17:16:37 default_worker.1     | /usr/src/app/vendor/bundle/ruby/3.3.0/gems/sidekiq-7.3.1/lib/sidekiq/component.rb:19:in `block in safe_thread'
17:16:37 default_worker.1     | 2024-08-21T17:16:37.400Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c INFO: Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job 1d3269a77f8f4e53b57bd96c
17:16:37 default_worker.1     | 2024-08-21T17:16:37.400Z pid=138 tid=1826 class=ProcessUploadedFileJob jid=1d3269a77f8f4e53b57bd96c elapsed=0.016 INFO: fail
17:16:37 default_worker.1     | 2024-08-21T17:16:37.400Z pid=138 tid=1826 WARN: {"context":"Job raised exception","job":{"retry":10,"queue":"default","wrapped":"ProcessUploadedFileJob","args":[{"job_class":"ProcessUploadedFileJob","job_id":"40e1a8d2-9c9d-47f1-8f88-01fab9f2eb86","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[1,{"id":"99cd5e222e75801eb0e5a57c3f57520e.zip","storage":"cache","metadata":{"filename":"ok-trophy-model_files.zip","size":5041038,"mime_type":"application/zip","_aj_symbol_keys":[]},"_aj_symbol_keys":[]}],"executions":0,"exception_executions":{},"locale":"en","timezone":"UTC","enqueued_at":"2024-08-21T12:54:42.787162398Z","scheduled_at":null}],"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","jid":"1d3269a77f8f4e53b57bd96c","created_at":1724244882.7872121,"enqueued_at":1724260597.3840382,"error_message":"Validation failed: Actor must exist","error_class":"ActiveRecord::RecordInvalid","failed_at":1724260597.399814,"retry_count":9,"retried_at":1724254010.16957,"processor":"manyfold-0:138"}}
17:16:37 default_worker.1     | 2024-08-21T17:16:37.400Z pid=138 tid=1826 WARN: ActiveRecord::RecordInvalid: Validation failed: Actor must exist
17:16:37 default_worker.1     | 2024-08-21T17:16:37.402Z pid=138 tid=1826 WARN: app/models/concerns/followable.rb:26:in `post_creation_activity'
17:16:37 default_worker.1     | app/jobs/process_uploaded_file_job.rb:17:in `perform'

```

Not entirely sure what im looking at here, but hopefully it's of some use to you

**Comment by Floppy** [comment]
Thanks, that's perfect :)
