### ISSUE TITLE
Member user can't see models

### ISSUE THREAD

**Issue by Floppy** [manyfold3d/manyfold#2907]
Reported on Matrix by `grecco`.

**Comment by Grecco24** [comment]
### Test on Version: 0.81.0 (f29e141a)

***Model: Any logged-in local user***
***User: only member role***
```
19:01:53 rails.1              | I, [2024-10-10T19:01:53.391097 #232]  INFO -- : [1f63283a-7600-487e-b023-db6c8b98e523] {"method":"GET","path":"/models/4v5Hxclc","format":"html","controller":"ModelsController","action":"show","status":404,"allocations":6689,"duration":114.61,"view":0.0,"db":27.2,"@timestamp":"2024-10-10T19:01:53.390Z","@version":"1","message":"[404] GET /models/4v5Hxclc (ModelsController#show)"}
19:01:53 rails.1              | F, [2024-10-10T19:01:53.397692 #232] FATAL -- : [1f63283a-7600-487e-b023-db6c8b98e523]
19:01:53 rails.1              | [1f63283a-7600-487e-b023-db6c8b98e523] ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
19:01:53 rails.1              | [1f63283a-7600-487e-b023-db6c8b98e523]
19:01:53 rails.1              | [1f63283a-7600-487e-b023-db6c8b98e523] app/controllers/application_controller.rb:98:in `user_not_authorized'
```

***Model: removed "Any logged-in local user"***
***User: only member role***
Can't see the model anymore

***Model: reapplied "Any logged-in local user"***
***User: only member role***
```
19:04:19 rails.1              | I, [2024-10-10T19:04:19.890095 #232]  INFO -- : [280eb4e1-d160-4759-810c-18928c3f6321] {"method":"GET","path":"/models/4v5Hxclc","format":"html","controller":"ModelsController","action":"show","status":404,"allocations":6464,"duration":102.92,"view":0.0,"db":25.58,"@timestamp":"2024-10-10T19:04:19.889Z","@version":"1","message":"[404] GET /models/4v5Hxclc (ModelsController#show)"}
19:04:19 rails.1              | F, [2024-10-10T19:04:19.899601 #232] FATAL -- : [280eb4e1-d160-4759-810c-18928c3f6321]
19:04:19 rails.1              | [280eb4e1-d160-4759-810c-18928c3f6321] ActiveRecord::RecordNotFound (ActiveRecord::RecordNotFound):
19:04:19 rails.1              | [280eb4e1-d160-4759-810c-18928c3f6321]
19:04:19 rails.1              | [280eb4e1-d160-4759-810c-18928c3f6321] app/controllers/application_controller.rb:98:in `user_not_authorized'
```

***Model: Any logged-in local user & User explicitly added***
***User: only member role***
User can see the model again
```
19:09:01 rails.1              | W, [2024-10-10T19:09:01.705048 #247]  WARN -- : [cc550741-7f37-4f28-bbe3-2bf5384635f7] Scoped order is ignored, it's forced to be batch order.
19:09:01 rails.1              | I, [2024-10-10T19:09:01.751253 #247]  INFO -- : [cc550741-7f37-4f28-bbe3-2bf5384635f7] {"method":"GET","path":"/models/4v5Hxclc","format":"html","controller":"ModelsController","action":"show","status":200,"allocations":41273,"duration":401.63,"view":177.0,"db":130.05,"@timestamp":"2024-10-10T19:09:01.750Z","@version":"1","message":"[200] GET /models/4v5Hxclc (ModelsController#show)"}
19:09:01 rails.1              | I, [2024-10-10T19:09:01.988393 #232]  INFO -- : [5ea43cf8-bc20-4cdc-a71d-052b5dc83d8f] {"method":"GET","path":"/models/4v5Hxclc/model_files/2sMFHm5g.jpg","format":"jpeg","controller":"ModelFilesController","action":"show","status":200,"allocations":13997,"duration":210.15,"view":0.0,"db":95.4,"@timestamp":"2024-10-10T19:09:01.988Z","@version":"1","message":"[200] GET /models/4v5Hxclc/model_files/2sMFHm5g.jpg (ModelFilesController#show)"}
19:09:02 rails.1              | I, [2024-10-10T19:09:02.040257 #236]  INFO -- : [6d78b2fc-420f-4dc3-a6a9-4ac93dd88b82] {"method":"GET","path":"/models/4v5Hxclc/model_files/kp7zShKf.jpg","format":"jpeg","controller":"ModelFilesController","action":"show","status":200,"allocations":17687,"duration":235.45,"view":0.0,"db":197.93,"@timestamp":"2024-10-10T19:09:02.039Z","@version":"1","message":"[200] GET /models/4v5Hxclc/model_files/kp7zShKf.jpg (ModelFilesController#show)"}
19:09:02 rails.1              | I, [2024-10-10T19:09:02.061372 #247]  INFO -- : [252ff9f9-c8b3-4da9-8d2a-b97e3afc9ee4] {"method":"GET","path":"/models/4v5Hxclc/model_files/R8gtRs7n.stl","format":"stl","controller":"ModelFilesController","action":"show","status":200,"allocations":5699,"duration":81.62,"view":0.0,"db":23.91,"@timestamp":"2024-10-10T19:09:02.061Z","@version":"1","message":"[200] GET /models/4v5Hxclc/model_files/R8gtRs7n.stl (ModelFilesController#show)"}
19:09:02 rails.1              | I, [2024-10-10T19:09:02.110587 #236]  INFO -- : [124fc68e-e7e9-42a2-8ffc-8bd3e8c5dd39] {"method":"GET","path":"/models/4v5Hxclc/model_files/9BTkWXl0.jpg","format":"jpeg","controller":"ModelFilesController","action":"show","status":200,"allocations":22093,"duration":296.34,"view":0.0,"db":175.1,"@timestamp":"2024-10-10T19:09:02.110Z","@version":"1","message":"[200] GET /models/4v5Hxclc/model_files/9BTkWXl0.jpg (ModelFilesController#show)"}
```
