### ISSUE TITLE
HTTP Error on Model & updating creator

### ISSUE THREAD

**Issue by Zottelchen** [manyfold3d/manyfold#3336]
**Describe the bug**
Some specific models can not be viewed in Version 0.91.3 (5bc25839).

**To Reproduce**
1. Search for specific model
2. Try to open the page
3. See the error message
4. Find issue about something similiar happening with creators #3304 
5. Try to remove (Patreon) link from creator
6. Also see error message

**Expected behavior**
The pages should load

**Screenshots**
![image](https://github.com/user-attachments/assets/f831e001-b619-44d1-9311-82c22b03220e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Electron

**Additional context**
Log Output when viewing model:
```
app-1          | 18:48:01 rails.1              | F, [2024-12-27T18:48:01.678165 #173] FATAL -- : [030b57fc-1b9e-43c2-89ca-822c62012d79]
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] ActionView::Template::Error (undefined method `at_address' for nil):
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]
app-1          | 18:48:01 rails.1              | Causes:
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] NoMethodError (undefined method `at_address' for nil)
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     2:   <%= tag.meta property: "og:type", content: "website" %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     3:   <%= tag.meta property: "og:image", content: model_model_file_url(@model, @model.preview_file, format: @model.preview_file.extension) if @model.preview_file&.is_image? && !@model.sensitive %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     4:   <%= tag.meta name: "description", content: truncate(sanitize(@model.notes), length: 80) if @model.notes.present? %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     5:   <%= tag.meta name: "fediverse:creator", content: "@#{@model.creator.federails_actor.at_address}" if @model.creator %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     6: <% end %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     7:
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]     8: <% content_for :page_header do %>
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79]
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] app/views/models/show.html.erb:5
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] app/views/models/show.html.erb:1
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] app/controllers/models_controller.rb:36:in `block (2 levels) in show'
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] app/controllers/models_controller.rb:21:in `show'
app-1          | 18:48:01 rails.1              | [030b57fc-1b9e-43c2-89ca-822c62012d79] app/controllers/application_controller.rb:86:in `switch_locale'
```

Log Output when removing link from creator:
```
app-1          | 18:52:23 rails.1              | I, [2024-12-27T18:52:23.901329 #154]  INFO -- : [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] {"method":"PATCH","path":"/creators/kb3d","format":"html","controller":"CreatorsController","action":"update","status":500,"allocations":5498,"duration":73.29,"view":0.0,"db":19.52,"@timestamp":"2024-12-27T18:52:23.901Z","@version":"1","message":"[500] PATCH /creators/kb3d (CreatorsController#update)"}
app-1          | 18:52:23 rails.1              | F, [2024-12-27T18:52:23.902873 #154] FATAL -- : [d33f4711-3199-4ef5-a0b3-1dae113d9cd0]
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] NameError (undefined local variable or method `create_actor' for an instance of Creator):
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0]
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] app/models/concerns/federails_common.rb:8:in `actor'
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] app/models/concerns/followable.rb:30:in `followable_post_update_activity'
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] app/controllers/creators_controller.rb:66:in `update'
app-1          | 18:52:23 rails.1              | [d33f4711-3199-4ef5-a0b3-1dae113d9cd0] app/controllers/application_controller.rb:86:in `switch_locale'
```

**Comment by Floppy** [comment]
Thanks! I'll get a fix out for that.
